Bundle lodash dependency from strong-globalize
This is a speculative fix to avoid the following `npm install` failure
that's triggered for certain timing of the order in which dependencies
are installed:

> strong-mesh-client@1.6.3 install
> workspace/strong-arc/e13f9a50/node_modules/strong-mesh-client
> node proxy/build-client.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'lodash/_MapCache'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (node_modules/loopback-boot/
                           node_modules/strong-globalize/
                           lib/globalize.js:14:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)